apiVersion: v1
kind: Namespace
metadata:
  name: dictionary
  labels:
    app: dictionary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-deployment
  namespace: dictionary
  labels:
    name: dictionary-dep
    tier: frontend
    app: dictionary
spec:
  replicas: 1
  template:
    metadata:
      name: dictionary-pod
      namespace: dictionary
      labels:
        name: dictionary-pd
        tier: frontend
        app: dictionary
    spec:
      containers:
        - name: dictionary
          image: boyapatihemanth/dictionary:v2
          ports:
            - name: dictionary-port
              containerPort: 80
  selector:
    matchLabels:
      name: dictionary-pd

---

apiVersion: v1
kind: Service
metadata:
  name: dictionary-node-port
  namespace: dictionary
  labels:
    name: dictionary-node-port
    tier: network
    app: dictionary
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80 # defaults to port if not provided
      nodePort: 32000 #30000 - 32767
      protocol: TCP
  selector:
    name: dictionary-pd